#! /bin/sh

####################################################
#                                                   #
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗    #
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║    #
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║    #
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║    #
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║    #
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝    # 
#####################################################


pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d 1 2 3 4 5

########## Window Settings ##############
bspc config border_width         2
bspc config window_gap           10  
bspc config focus_follows_pointer	true
bspc config split_ratio          0.50 
bspc config borderless_monocle   true
bspc config gapless_monocle      true

########## Border Colors #################
bspc config focused_border_color "#2E3440"
bspc config normal_border_color "#2E3440"

######### Program settings ################
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a Firefox desktop='^2'

######### Other Settings ################
xsetroot -cursor_name left_ptr &
xbacklight -set 30

######## MY picom :) ###################
picom  &

######## THe real beauty behind rice ####
nitrogen --restore &

######### My Bar ###############
polybar main 
