#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V VI VII 

############Window Settings ####################
bspc config border_width         1
bspc config window_gap           5 
bspc config focus_follows_pointer	true
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config top_padding 	 20 

########## Border Colors #################
bspc config focused_border_color "#353b45"
bspc config normal_border_color "#353b45"

######### Program settings ################
bspc rule -a spotify ='^5' 
bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a Firefox desktop='^2'
bspc rule -a Zathura state=tiled 
dunst & 

######### Other Settings ################
xsetroot -cursor_name left_ptr &
xbacklight -set 30
xinput set-prop 12 309 1

######## MY picom :) ###################
#picom --config ~/.config/picom/picom.conf --experimental-backends &

######## THe real beauty behind rice ####
xwallpaper --zoom ~/wall/forest1.png 

######### My Bar ###############
polybar example -c ~/.config/polybar/config.ini 
